/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_exascale_optimizer_testing_Rootbeer */

#ifndef _Included_com_exascale_optimizer_testing_Rootbeer
#define _Included_com_exascale_optimizer_testing_Rootbeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_exascale_optimizer_testing_Rootbeer
 * Method:    extendKernel
 * Signature: ([F[B[FIIII)V
 */
JNIEXPORT void JNICALL Java_com_exascale_optimizer_testing_Rootbeer_extendKernel
  (JNIEnv *, jobject, jfloatArray, jbyteArray, jfloatArray, jint, jint, jint, jint);

/*
 * Class:     com_exascale_optimizer_testing_Rootbeer
 * Method:    parseKernel
 * Signature: (ILjava/lang/String;IILjava/util/ArrayList;Ljava/util/ArrayList;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_exascale_optimizer_testing_Rootbeer_parseKernel
  (JNIEnv *, jobject, jint, jstring, jint, jint, jobject, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
