version: "2.0"
services:
  node:
    image: iitdbgroup/hrdbms:dev-env
    container_name: "hrdbmsnode"
    volumes:
        - ../../../:/home/hrdbms/app:z
        - ./hparms:/home/hrdbms/hparms
        - ./nodes.cfg:/home/hrdbms/nodes.cfg
  coordinator:
     extends:
        service: node
     ports:
        - "5010:5010"
     depends_on:
        - worker
        - worker2
     container_name: "hrdbmscoordinator"
     networks:
        appnet:
          ipv4_address: 17.17.0.2
  worker:
     container_name: "hrdbmsworker"
     extends:
        service: node
     ports:
        - "5015:5015"
     networks:
        appnet:
          ipv4_address: 17.17.0.3
  worker2:
     container_name: "hrdbmsworker2"
     extends:
        service: node
     ports:
        - "5020:5015"
     networks:
        appnet:
          ipv4_address: 17.17.0.4
networks:
  appnet:
    external: true
